import type { TestDifficulty } from './testsData';

type ExtraQuestion = {
  id: string;
  category: string;
  difficulty: TestDifficulty;
  text: string;
  options: string[];
  correctIndex: number;
  explanation: string;
};

/** Extra questions so each category matches the catalog questionCount. */
export const EXTRA_QUESTIONS: ExtraQuestion[] = [
  // —— signs (need 20 total; +14)
  {
    id: 'q31',
    category: 'signs',
    difficulty: 'easy',
    text: 'A round white sign with a black arrow curving left usually means:',
    options: ['No left turn', 'Mandatory left curve / keep left', 'Detour only', 'One-way ends'],
    correctIndex: 1,
    explanation: 'White/blue circular signs often give mandatory direction instructions.',
  },
  {
    id: 'q32',
    category: 'signs',
    difficulty: 'medium',
    text: 'Two parallel solid yellow lines in the center of the road generally mean:',
    options: [
      'Passing is allowed both ways',
      'No passing from either direction',
      'Parking only',
      'Bus lane ahead',
    ],
    correctIndex: 1,
    explanation: 'Double solid center lines usually prohibit crossing/passing.',
  },
  {
    id: 'q33',
    category: 'signs',
    difficulty: 'easy',
    text: 'A rectangular blue “P” sign typically indicates:',
    options: ['No parking', 'Parking allowed', 'Police checkpoint', 'Private road'],
    correctIndex: 1,
    explanation: 'A blue P sign marks a parking area or parking permission.',
  },
  {
    id: 'q34',
    category: 'signs',
    difficulty: 'hard',
    text: 'A sign with a red circle around a truck means:',
    options: [
      'Trucks must use this lane',
      'Trucks are prohibited',
      'Truck parking only',
      'Trucks have priority',
    ],
    correctIndex: 1,
    explanation: 'A red prohibition circle over a vehicle type bans that vehicle.',
  },
  {
    id: 'q35',
    category: 'signs',
    difficulty: 'medium',
    text: 'A diamond-shaped orange sign is most often used for:',
    options: ['Highway exits', 'Temporary work zones / construction', 'School buses only', 'Fuel stations'],
    correctIndex: 1,
    explanation: 'Orange diamond signs warn about temporary road works and hazards.',
  },
  {
    id: 'q36',
    category: 'signs',
    difficulty: 'easy',
    text: 'A “No U-turn” sign means:',
    options: [
      'U-turns are allowed at night',
      'You must not make a U-turn',
      'U-turns only for taxis',
      'U-turns require hazard lights',
    ],
    correctIndex: 1,
    explanation: 'The sign forbids turning the vehicle around to go the opposite way.',
  },
  {
    id: 'q37',
    category: 'signs',
    difficulty: 'medium',
    text: 'A sign showing a percentage grade (e.g. 10%) warns about:',
    options: ['Speed cameras', 'A steep hill', 'Tunnel height', 'Fuel consumption tax'],
    correctIndex: 1,
    explanation: 'Grade signs warn of steep uphill or downhill sections.',
  },
  {
    id: 'q38',
    category: 'signs',
    difficulty: 'easy',
    text: 'A red octagon almost always means:',
    options: ['Yield', 'Stop', 'No entry', 'One way'],
    correctIndex: 1,
    explanation: 'The octagon shape is reserved for STOP.',
  },
  {
    id: 'q39',
    category: 'signs',
    difficulty: 'hard',
    text: 'A sign with two arrows pointing in opposite directions usually indicates:',
    options: ['Dead end', 'Two-way traffic', 'Overtaking lane', 'Roundabout exit only'],
    correctIndex: 1,
    explanation: 'It warns that traffic may come from the opposite direction.',
  },
  {
    id: 'q40',
    category: 'signs',
    difficulty: 'medium',
    text: 'A “End of speed limit” sign means:',
    options: [
      'You must stop',
      'Previous special limit ends; general rules apply',
      'Speed cameras ahead',
      'Minimum speed becomes mandatory',
    ],
    correctIndex: 1,
    explanation: 'It cancels the posted special limit so default limits return.',
  },
  {
    id: 'q41',
    category: 'signs',
    difficulty: 'easy',
    text: 'A children / school warning sign means you should:',
    options: [
      'Ignore if no children are visible',
      'Expect children and reduce speed',
      'Use the horn constantly',
      'Park on the sidewalk',
    ],
    correctIndex: 1,
    explanation: 'Slow down and stay alert in areas where children may cross.',
  },
  {
    id: 'q42',
    category: 'signs',
    difficulty: 'medium',
    text: 'A “No overtaking” sign means:',
    options: [
      'You may pass if faster',
      'Passing other vehicles is forbidden in that zone',
      'Only trucks may pass',
      'Passing is allowed on weekends',
    ],
    correctIndex: 1,
    explanation: 'Do not overtake while the restriction applies.',
  },
  {
    id: 'q43',
    category: 'signs',
    difficulty: 'hard',
    text: 'A lane-control sign with a red X above a lane means:',
    options: [
      'That lane is closed to traffic',
      'That lane is for buses only',
      'You must use that lane',
      'Emergency vehicles only may enter',
    ],
    correctIndex: 0,
    explanation: 'A red X indicates the lane is closed — do not drive in it.',
  },
  {
    id: 'q44',
    category: 'signs',
    difficulty: 'easy',
    text: 'A railway crossing warning sign means:',
    options: [
      'Train parking area',
      'Prepare to stop if a train is approaching',
      'Freeway entrance',
      'No trucks allowed forever',
    ],
    correctIndex: 1,
    explanation: 'Approach carefully and be ready to stop for trains.',
  },

  // —— priority (need 15; +10)
  {
    id: 'q45',
    category: 'priority',
    difficulty: 'easy',
    text: 'On a narrow bridge with an oncoming vehicle, who should usually yield?',
    options: [
      'Whoever arrives second',
      'The driver who can do so more safely / as signed',
      'The larger vehicle always',
      'Nobody — both proceed',
    ],
    correctIndex: 1,
    explanation: 'Follow signs and give way so both vehicles can pass safely.',
  },
  {
    id: 'q46',
    category: 'priority',
    difficulty: 'medium',
    text: 'When turning left across oncoming traffic, you must:',
    options: [
      'Turn immediately on green',
      'Yield to oncoming vehicles going straight',
      'Expect others to stop for you',
      'Use the horn instead of yielding',
    ],
    correctIndex: 1,
    explanation: 'Oncoming traffic going straight generally has priority.',
  },
  {
    id: 'q47',
    category: 'priority',
    difficulty: 'easy',
    text: 'A police officer directing traffic overrides:',
    options: [
      'Only parking signs',
      'Traffic lights and normal priority rules',
      'Nothing — lights always win',
      'Only pedestrian signals',
    ],
    correctIndex: 1,
    explanation: 'Follow the officer’s directions even if they conflict with lights.',
  },
  {
    id: 'q48',
    category: 'priority',
    difficulty: 'hard',
    text: 'At a four-way stop, if two vehicles arrive together from different roads:',
    options: [
      'The larger vehicle goes first',
      'The vehicle on the right usually goes first',
      'Both reverse',
      'The faster driver goes first',
    ],
    correctIndex: 1,
    explanation: 'Equal arrival typically follows right-hand priority (local rules apply).',
  },
  {
    id: 'q49',
    category: 'priority',
    difficulty: 'medium',
    text: 'Leaving a private driveway onto a public road, you should:',
    options: [
      'Expect priority over road traffic',
      'Yield to vehicles and pedestrians on the road',
      'Enter at full speed',
      'Only yield to trucks',
    ],
    correctIndex: 1,
    explanation: 'Traffic on the public road has priority over vehicles exiting private property.',
  },
  {
    id: 'q50',
    category: 'priority',
    difficulty: 'easy',
    text: 'Buses pulling out from a stop in cities often require you to:',
    options: [
      'Block them intentionally',
      'Give them room / yield when required by local rules',
      'Overtake on the sidewalk',
      'Ignore signals',
    ],
    correctIndex: 1,
    explanation: 'Many areas require yielding to buses re-entering traffic — check local law.',
  },
  {
    id: 'q51',
    category: 'priority',
    difficulty: 'hard',
    text: 'When two vehicles meet on a steep hill where one must reverse:',
    options: [
      'The downhill vehicle usually has more control to reverse if needed',
      'Always the uphill vehicle reverses',
      'Both stop forever',
      'Flip a coin',
    ],
    correctIndex: 0,
    explanation: 'Often the downhill driver is better positioned to reverse — follow local practice and signs.',
  },
  {
    id: 'q52',
    category: 'priority',
    difficulty: 'medium',
    text: 'A “priority road” sign means:',
    options: [
      'You must stop at every junction',
      'You generally have priority at upcoming intersections until cancelled',
      'Parking is free',
      'Only buses may use the road',
    ],
    correctIndex: 1,
    explanation: 'Priority-road signing gives you precedence until an end-of-priority sign.',
  },
  {
    id: 'q53',
    category: 'priority',
    difficulty: 'easy',
    text: 'Cyclists on the roadway are:',
    options: [
      'Not road users',
      'Road users you must respect and yield to when required',
      'Allowed only on sidewalks',
      'Always required to stop for cars',
    ],
    correctIndex: 1,
    explanation: 'Treat cyclists as vulnerable road users and share the road safely.',
  },
  {
    id: 'q54',
    category: 'priority',
    difficulty: 'medium',
    text: 'At a T-junction without signs, traffic on the through road usually:',
    options: [
      'Must stop for the joining road',
      'Has priority over vehicles joining from the stem of the T',
      'Must always reverse',
      'Shares priority randomly',
    ],
    correctIndex: 1,
    explanation: 'Vehicles on the continuing road typically have priority.',
  },

  // —— lights (need 12; +7)
  {
    id: 'q55',
    category: 'lights',
    difficulty: 'easy',
    text: 'A steady green light means:',
    options: [
      'Go if the intersection is clear and it is safe',
      'Speed up regardless of traffic',
      'Stop first then go',
      'Only turn left',
    ],
    correctIndex: 0,
    explanation: 'Green allows movement when the path is clear and safe.',
  },
  {
    id: 'q56',
    category: 'lights',
    difficulty: 'medium',
    text: 'If a traffic light is dark / out of order, you should usually:',
    options: [
      'Treat it like a four-way stop / proceed with extreme caution',
      'Drive through at highway speed',
      'Ignore other vehicles',
      'Only trucks may pass',
    ],
    correctIndex: 0,
    explanation: 'Unpowered signals are treated carefully — often like an all-way stop.',
  },
  {
    id: 'q57',
    category: 'lights',
    difficulty: 'easy',
    text: 'A pedestrian red man / “don’t walk” signal means pedestrians should:',
    options: [
      'Start crossing quickly',
      'Not start crossing',
      'Run across anyway',
      'Wave cars through',
    ],
    correctIndex: 1,
    explanation: 'Do not begin crossing on a don’t-walk / red pedestrian signal.',
  },
  {
    id: 'q58',
    category: 'lights',
    difficulty: 'hard',
    text: 'A green light does NOT give you the right to:',
    options: [
      'Enter an intersection blocked by traffic',
      'Drive forward when clear',
      'Turn with a green arrow',
      'Proceed carefully',
    ],
    correctIndex: 0,
    explanation: 'Never enter if you will block the intersection — even on green.',
  },
  {
    id: 'q59',
    category: 'lights',
    difficulty: 'medium',
    text: 'Lane signals showing a green arrow pointing down mean:',
    options: [
      'Lane closed',
      'You may use that lane',
      'Reverse only',
      'Parking lane',
    ],
    correctIndex: 1,
    explanation: 'A downward green arrow indicates the lane is open for traffic.',
  },
  {
    id: 'q60',
    category: 'lights',
    difficulty: 'easy',
    text: 'You arrive at a red light and need to turn where turns on red are allowed after stop. You must:',
    options: [
      'Turn without stopping',
      'Stop fully, yield, then turn if permitted and safe',
      'Wait for green always',
      'Honk and turn',
    ],
    correctIndex: 1,
    explanation: 'Where turn-on-red is legal, a full stop and yield are still required.',
  },
  {
    id: 'q61',
    category: 'lights',
    difficulty: 'hard',
    text: 'A yellow arrow typically means:',
    options: [
      'Protected turn is ending — prepare to stop if unsafe to complete',
      'Turn is forbidden forever',
      'Accelerate hard',
      'Parking allowed',
    ],
    correctIndex: 0,
    explanation: 'Yellow arrow warns the protected turn phase is ending.',
  },

  // —— parking (need 16; +12)
  {
    id: 'q62',
    category: 'parking',
    difficulty: 'easy',
    text: 'Parking within an intersection is:',
    options: ['Allowed at night', 'Generally forbidden', 'Allowed with hazards on', 'Required'],
    correctIndex: 1,
    explanation: 'Do not park in intersections — it blocks traffic and is unsafe.',
  },
  {
    id: 'q63',
    category: 'parking',
    difficulty: 'medium',
    text: 'When parking downhill with a curb, turn wheels:',
    options: [
      'Away from the curb',
      'Toward the curb',
      'Straight only',
      'Randomly',
    ],
    correctIndex: 1,
    explanation: 'Downhill: wheels toward curb so the car rolls into the curb if brakes fail.',
  },
  {
    id: 'q64',
    category: 'parking',
    difficulty: 'easy',
    text: 'Leaving insufficient space for a fire hydrant access is:',
    options: ['Fine', 'Usually illegal and dangerous', 'Required', 'Only wrong in summer'],
    correctIndex: 1,
    explanation: 'Keep clear of hydrants so emergency services can access them.',
  },
  {
    id: 'q65',
    category: 'parking',
    difficulty: 'medium',
    text: 'Double parking (parking beside a parked car in the lane) is:',
    options: [
      'Acceptable for 1 minute',
      'Generally not allowed',
      'Required in cities',
      'Allowed with music on',
    ],
    correctIndex: 1,
    explanation: 'Double parking obstructs traffic and is typically prohibited.',
  },
  {
    id: 'q66',
    category: 'parking',
    difficulty: 'hard',
    text: 'Parking on a soft shoulder at night without lights/reflectors is risky because:',
    options: [
      'It improves visibility',
      'Other drivers may not see you in time',
      'It charges the battery',
      'It is always mandatory',
    ],
    correctIndex: 1,
    explanation: 'Poor visibility makes roadside stops dangerous — use lights and safe spots.',
  },
  {
    id: 'q67',
    category: 'parking',
    difficulty: 'easy',
    text: 'Before opening a car door into traffic (Dutch reach / dooring prevention), you should:',
    options: [
      'Open quickly without looking',
      'Check mirrors and blind area for cyclists/vehicles',
      'Throw the door fully open',
      'Only check the radio',
    ],
    correctIndex: 1,
    explanation: 'Always check for cyclists and cars before opening the door.',
  },
  {
    id: 'q68',
    category: 'parking',
    difficulty: 'medium',
    text: 'Disabled parking bays may be used by:',
    options: [
      'Anyone for 5 minutes',
      'Vehicles with valid disability permits',
      'Only motorcycles',
      'Delivery drones',
    ],
    correctIndex: 1,
    explanation: 'Accessible bays are reserved for permit holders.',
  },
  {
    id: 'q69',
    category: 'parking',
    difficulty: 'easy',
    text: 'Parking facing against the flow of traffic on a two-way street is:',
    options: [
      'Usually preferred',
      'Often illegal / unsafe',
      'Required at night',
      'Only for electric cars',
    ],
    correctIndex: 1,
    explanation: 'Park in the direction of traffic unless signs allow otherwise.',
  },
  {
    id: 'q70',
    category: 'parking',
    difficulty: 'hard',
    text: 'Stopping on a motorway / expressway shoulder is allowed:',
    options: [
      'To make phone calls casually',
      'Only for emergencies or when directed',
      'For picnics',
      'To practice parking',
    ],
    correctIndex: 1,
    explanation: 'Hard shoulders are for emergencies, not routine stops.',
  },
  {
    id: 'q71',
    category: 'parking',
    difficulty: 'medium',
    text: 'A “No stopping” zone means:',
    options: [
      'You may wait with engine off',
      'You must not stop except if traffic forces you / emergency',
      'Parking is fine',
      'Loading is always allowed',
    ],
    correctIndex: 1,
    explanation: 'No stopping is stricter than no parking — do not halt there.',
  },
  {
    id: 'q72',
    category: 'parking',
    difficulty: 'easy',
    text: 'When leaving a parallel parking space, you should:',
    options: [
      'Exit without signaling',
      'Signal, check blind spots, and merge carefully',
      'Reverse into traffic at speed',
      'Rely only on pedestrians to warn you',
    ],
    correctIndex: 1,
    explanation: 'Signal and check thoroughly before rejoining the lane.',
  },
  {
    id: 'q73',
    category: 'parking',
    difficulty: 'medium',
    text: 'Parking too close to a bus stop bay can:',
    options: [
      'Help buses',
      'Block buses and passengers — usually forbidden',
      'Increase your score',
      'Be required by law',
    ],
    correctIndex: 1,
    explanation: 'Keep bus stops clear for safe boarding and bus access.',
  },

  // —— maneuvers (need 18; +13)
  {
    id: 'q74',
    category: 'maneuvers',
    difficulty: 'easy',
    text: 'The correct order before a lane change is typically:',
    options: [
      'Move first, then signal',
      'Mirrors → signal → blind spot → move when safe',
      'Brake → accelerate → signal',
      'Honk → swerve',
    ],
    correctIndex: 1,
    explanation: 'Observe, signal, check blind spot, then change lanes smoothly.',
  },
  {
    id: 'q75',
    category: 'maneuvers',
    difficulty: 'medium',
    text: 'When merging onto a highway, you should:',
    options: [
      'Stop at the end of every ramp',
      'Match traffic speed and merge into a gap',
      'Enter at 20 km/h always',
      'Expect others to always brake for you',
    ],
    correctIndex: 1,
    explanation: 'Use the acceleration lane to match speed and merge safely.',
  },
  {
    id: 'q76',
    category: 'maneuvers',
    difficulty: 'hard',
    text: 'Overtaking a cyclist requires:',
    options: [
      'Passing with inches of clearance',
      'Giving safe lateral space and only when clear ahead',
      'Honking continuously while passing',
      'Driving on the sidewalk',
    ],
    correctIndex: 1,
    explanation: 'Leave generous space and pass only when the road ahead is clear.',
  },
  {
    id: 'q77',
    category: 'maneuvers',
    difficulty: 'easy',
    text: 'A three-point turn should be done:',
    options: [
      'On blind curves',
      'Only where safe, legal, and visibility is good',
      'On highways',
      'Without checking mirrors',
    ],
    correctIndex: 1,
    explanation: 'Choose a safe place with clear sight lines.',
  },
  {
    id: 'q78',
    category: 'maneuvers',
    difficulty: 'medium',
    text: 'When another vehicle is overtaking you, you should:',
    options: [
      'Speed up to race',
      'Keep steady speed and allow them to pass safely',
      'Drift into their lane',
      'Brake abruptly without reason',
    ],
    correctIndex: 1,
    explanation: 'Help the pass by keeping a predictable line and speed.',
  },
  {
    id: 'q79',
    category: 'maneuvers',
    difficulty: 'hard',
    text: 'Entering a roundabout in the wrong lane for your exit is best fixed by:',
    options: [
      'Cutting across lanes abruptly',
      'Continuing safely around and exiting correctly when possible',
      'Stopping in the circle',
      'Reversing in the roundabout',
    ],
    correctIndex: 1,
    explanation: 'Do not stop or cut across — go around again if needed.',
  },
  {
    id: 'q80',
    category: 'maneuvers',
    difficulty: 'easy',
    text: 'Before reversing you must:',
    options: [
      'Only use the radio',
      'Ensure the path is clear behind and around',
      'Accelerate immediately',
      'Close your eyes briefly',
    ],
    correctIndex: 1,
    explanation: 'Check all around — children and obstacles are easy to miss.',
  },
  {
    id: 'q81',
    category: 'maneuvers',
    difficulty: 'medium',
    text: 'A safe following gap in dry conditions is often described as:',
    options: [
      'Zero seconds',
      'About two seconds or more',
      'One car length at any speed',
      'Whatever feels exciting',
    ],
    correctIndex: 1,
    explanation: 'The two-second rule (more in bad weather) helps maintain space.',
  },
  {
    id: 'q82',
    category: 'maneuvers',
    difficulty: 'hard',
    text: 'When skidding, a common recovery approach is to:',
    options: [
      'Slam brakes and spin the wheel randomly',
      'Ease off accelerator and steer into the skid smoothly',
      'Close your eyes',
      'Shift to reverse',
    ],
    correctIndex: 1,
    explanation: 'Reduce inputs and steer to regain traction — avoid panic braking.',
  },
  {
    id: 'q83',
    category: 'maneuvers',
    difficulty: 'easy',
    text: 'Using high beams toward oncoming drivers is:',
    options: [
      'Polite',
      'Dazzling and dangerous — dip lights in time',
      'Required in cities',
      'Fine if you wave',
    ],
    correctIndex: 1,
    explanation: 'Dip headlights so you do not blind oncoming traffic.',
  },
  {
    id: 'q84',
    category: 'maneuvers',
    difficulty: 'medium',
    text: 'Pulling away from the curb into traffic requires:',
    options: [
      'No signal',
      'Signal and yield to vehicles already on the road',
      'Immediate acceleration without checks',
      'Driving on the wrong side',
    ],
    correctIndex: 1,
    explanation: 'Indicate and wait for a safe gap.',
  },
  {
    id: 'q85',
    category: 'maneuvers',
    difficulty: 'hard',
    text: 'Passing a tram / streetcar boarding passengers on the street often means you must:',
    options: [
      'Squeeze past closely',
      'Stop and give passengers space where required',
      'Use the sidewalk',
      'Honk them aside',
    ],
    correctIndex: 1,
    explanation: 'Many cities require stopping for boarding/alighting passengers.',
  },
  {
    id: 'q86',
    category: 'maneuvers',
    difficulty: 'easy',
    text: 'Keeping both hands on the wheel (when safe/appropriate) helps you:',
    options: [
      'Text better',
      'Maintain control during sudden maneuvers',
      'Look stylish only',
      'Disable ABS',
    ],
    correctIndex: 1,
    explanation: 'Proper hand position improves control and reaction.',
  },

  // —— speed (need 14; +9)
  {
    id: 'q87',
    category: 'speed',
    difficulty: 'easy',
    text: 'The posted speed limit is:',
    options: [
      'A target you must always hit exactly',
      'A maximum in good conditions',
      'Only for trucks',
      'Optional advice',
    ],
    correctIndex: 1,
    explanation: 'Limits are maxima — slow down further when conditions demand.',
  },
  {
    id: 'q88',
    category: 'speed',
    difficulty: 'medium',
    text: 'In fog, a safe approach is to:',
    options: [
      'Use high beams only',
      'Reduce speed and use appropriate fog/low beams',
      'Tailgate the car ahead',
      'Ignore lane markings',
    ],
    correctIndex: 1,
    explanation: 'Slow down and use lights that do not reflect glare back at you.',
  },
  {
    id: 'q89',
    category: 'speed',
    difficulty: 'hard',
    text: 'Stopping distance increases most dramatically when:',
    options: [
      'Speed doubles (roughly more than doubles stopping distance)',
      'You add a passenger',
      'You clean the windshield',
      'You use cruise control on flat road',
    ],
    correctIndex: 0,
    explanation: 'Kinetic energy rises with speed squared — stopping needs much more distance.',
  },
  {
    id: 'q90',
    category: 'speed',
    difficulty: 'easy',
    text: 'A minimum speed limit sign means:',
    options: [
      'You must not drive slower than shown (unless unsafe)',
      'You must not drive faster',
      'Parking speed only',
      'Suggested music tempo',
    ],
    correctIndex: 0,
    explanation: 'Minimum speeds keep traffic flowing — still slow if safety requires.',
  },
  {
    id: 'q91',
    category: 'speed',
    difficulty: 'medium',
    text: 'On ice, you should:',
    options: [
      'Brake later and harder',
      'Drive much slower and avoid sudden inputs',
      'Use cruise control tightly',
      'Follow at half a second',
    ],
    correctIndex: 1,
    explanation: 'Ice needs gentle controls and much lower speeds.',
  },
  {
    id: 'q92',
    category: 'speed',
    difficulty: 'easy',
    text: 'Variable speed limit signs on motorways show:',
    options: [
      'Advertisements',
      'Temporary mandatory limits for current conditions',
      'Radio frequencies',
      'Parking prices',
    ],
    correctIndex: 1,
    explanation: 'Electronic limits adapt to traffic, weather, or incidents — obey them.',
  },
  {
    id: 'q93',
    category: 'speed',
    difficulty: 'hard',
    text: 'Driving significantly below the flow of highway traffic without reason can be:',
    options: [
      'Always safest',
      'Hazardous if it causes unsafe weaving around you',
      'Required by law always',
      'Only wrong at night',
    ],
    correctIndex: 1,
    explanation: 'Extremely slow driving can create conflicts — use hazards/pull over if needed.',
  },
  {
    id: 'q94',
    category: 'speed',
    difficulty: 'medium',
    text: 'The safest reaction when you see brake lights several cars ahead is often to:',
    options: [
      'Ignore them',
      'Ease off early and cover the brake',
      'Change lanes blindly',
      'Speed up to pass the queue',
    ],
    correctIndex: 1,
    explanation: 'Anticipate — early speed reduction prevents emergency stops.',
  },
  {
    id: 'q95',
    category: 'speed',
    difficulty: 'easy',
    text: 'In a residential area with children playing, you should:',
    options: [
      'Keep highway speed',
      'Slow down and stay ready to stop',
      'Use only the horn',
      'Close your eyes at crossings',
    ],
    correctIndex: 1,
    explanation: 'Expect unpredictable movement — reduce speed near children.',
  },
];
